name = "kwaadev"
type = "webpack"
usage_model = ''
compatibility_flags = []
site = {bucket = "./build",entry-point = "./workers-site"}
compatibility_date = "2021-10-17"
workers_dev = false
route = "kwaa.dev/*"